platform :ios, '9.0'
use_frameworks!
#use_modular_headers!
#inhibit_all_warnings!
target 'WLBaseTableViewDemo' do
    
    pod 'TSToolKit_Swift'
    
    pod 'MJRefresh'
    #,:modular_headers => false
end

pre_install do |installer|

Pod::PodTarget.send(:define_method, :static_framework?) { return true }

end
#pre_install do |installer|
    
    # workaround ``for` `https:``//github.com/CocoaPods/CocoaPods/issues/3289
    
#def installer.verify_no_static_framework_transitive_dependencies; end

#end
