platform :ios, '9.0'
use_frameworks!

target 'WLBaseTableViewDemo' do
    
    pod 'TSToolKit_Swift'
    
    pod 'MJRefresh' ,:modular_headers => true

end

pre_install do |installer|

Pod::PodTarget.send(:define_method, :static_framework?) { return true }

end